start:
  - cmd: terraform
    args:
      - init
  - cmd: terraform
    args:
      - apply
      - -auto-approve
destroy:
  - cmd: terraform
    args:
      - init
  - cmd: terraform
    args:
     - destroy
     - -auto-approve     